apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-ci-cd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nextjs-ci-cd
  template:
    metadata:
      labels:
        app: nextjs-ci-cd
    spec:
      containers:
        - name: nextjs-ci-cd-container
          image: kvait/nextjs-ci-cd
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: regcred
