apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextjs-ci-cd-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  ingressClassName: public
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextjs-ci-cd-service
                port:
                  number: 3000
